project/users/views.py
import base64

from flask import url_for, render_template, Blueprint, request, redirect, session, flash
from project import User, db ,host_address
import requests
import json
import flask_login
from project.users.froms import user_registration, user_login, forget_password_form, new_password
from project.users.models import Users
from project.request_module.apicalls import user_api

user_print = Blueprint('users', __name__, template_folder='templates/users')
api = user_api()


@user_print.route('/')
@flask_login.login_required
def index():
    return render_template('users.html', users_=flask_login.current_user.id)


@user_print.route('/signup', methods=['GET', 'POST'])
def registration():
    form = user_registration(request.form)
    flask_login.logout_user()
    Error_ = ""
    if request.method == 'POST':
        re_enter_pass = form.re_enter_pass.data
        password = form.password.data
        if (password == re_enter_pass):
            try:
                username = form.username.data
                email = form.email.data
                present = api.check_mail(email) #(json.loads((requests.get('{}/user_check/{}'.format(host_address,email))).text))['status']
                if not present:
                    res=api.register(username, email, password) #(json.loads((requests.post('{}/register/{}/{}/{}'.format(host_address,username, email, password))).text))['status']
                    if res:
                        return redirect(url_for('users.login'))
                Error_ = 'EXIST'
            except Exception as e:
                print(str(e))
                Error_ = 'VALUES_ERROR'
                return render_template('registration.html', form=form, Error_=Error_)
        else:
            Error_ = 'PASSWORD_NOT_MATCH'
            return render_template('registration.html', form=form, Error_=Error_)
    return render_template('registration.html', form=form, Error_=Error_)


@user_print.route('/signin', methods=['GET', 'POST'])
def login():
    form = user_login()
    Error_ = ""
    if request.method == 'POST':
        try:
            email_ = form.email.data
            password = form.password.data
            if len(email_) == 0 and len(password) == 0:
                return render_template('login.html', form=form, Error_=3)#no input
            else:
                print('here input' + email_)
                res = api.login(email_, password)#json.loads((requests.get('{}/login/{}/{}'.format(host_address,email_, password))).text)
                present = res['status']
                if present:
                    session['uid'] = res['user_id']
                    session['username'] = res['username']
                    user = User()
                    user.id = email_
                    print(flask_login.current_user.is_authenticated)
                    flask_login.login_user(user)
                    return redirect(url_for('users.index'))
                Error_ = 1 # not valid
                return render_template('login.html', form=form, Error_=Error_)
        except KeyError:
            Error_ = 2 # 'ERROR_ON_USER_KEY'
        except Exception as e:
            Error_ = 'ok'+str(e)
    print(Error_)
    if flask_login.current_user.is_authenticated:
        return redirect(url_for('users.index'))
    else:
        return render_template('login.html', form=form, Error_=Error_)


@user_print.route('/logout')
def logout():
    print('in logout')
    flask_login.logout_user()
    return redirect(url_for('users.login'))

@user_print.route('/forget_password',methods=['GET','POST'])
def forget_password():
    form = forget_password_form()
    if request.method == 'POST':
        req = {'mail_id': str(form.mail_id.data)}
        res = api.send_forget_pass(json.dumps(req))#json.loads(requests.post(f'{host_address}/project/share', json.dumps(req)).text)
        print(str(res))
        if res['status']:
            flash('Link Shared Successfully!')
        else:
            flash('Can\'t reach to your mail. Link is not Shared!')
    return render_template('forget_password.html',form=form)

@user_print.route('/new_password/<string:data>')
def visiter(data):
    req ={'mail_id':str(data)}
    res= json.dumps(api.get_user_by_mail(json.dumps(req)))
    return redirect(url_for('users.change',data=res))

@user_print.route('/new_password_create/<string:data>',methods=['POST','GET'])
def change(data):
    form = new_password()
    data = json.loads(data)['user']
    print(data['username'])
    req=dict()
    status = False
    ERROR =""
    if request.method=='POST':
        new_pass1 = form.pass1.data
        new_pass2 = form.re_enter.data
        if len(new_pass1)>0 and len(new_pass2)>0:
            if new_pass1==new_pass2:
                req['mail_id'] =data['email']
                req['new_password'] =form.re_enter.data
                res = api.send_changed_pass(json.dumps(req))
                print(res)
                if(res['status']):
                    status = True
                else:
                    flash("Can't process your request.")
            else:
                flash("Password not matched.")
        else:
            flash("Please enter New password.")
    return render_template('new_password.html',form=form,data=data,status=status)

project/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="icon" href="{{url_for('static',filename='favicon_nitor.png')}}"/>
     <link rel="stylesheet" href="{{url_for('static',filename='css/style.css')}}"/>
    <title>Demo Project</title>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<link href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
</head>
<body>
<!--Navbar section-->
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
  <a class="navbar-brand" href="#">
      <img style="width: 50%;" src="{{url_for('static',filename='logo-edited.png')}}"/>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNav">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      {%if not current_user.is_authenticated%}
      <li class="nav-item ">
        <a class="nav-link" href="{{url_for('index')}}">Home</a>
      </li>
      {%else%}
      <li class="nav-item ">
        <a class="nav-link" href="{{url_for('users.index')}}">Dashboard</a>
      </li>
      <li class="nav-item ">
        <a class="nav-link" href="{{url_for('project.index')}}">Projects</a>
      </li>
      {%endif%}
    </ul>
      {%if current_user.is_authenticated%}
        <div class="form-inline my-2 my-lg-0">
          <a href="{{url_for('users.logout')}}">
            <button class="btn btn-outline-success my-2 my-sm-0"><span class="btn-outline-info" style="color:white">{{session['username']}}</span> Sign out</button>
          </a>
        </div>
    {%else%}
    {% set ur=request.path%}
    {%if not ur=='/users/signin'%}
     <div class="form-inline my-2 my-lg-0">
          <a href="{{url_for('users.login')}}">
            <button class="btn btn-outline-success my-2 my-sm-0">Sign in</button>
          </a>
        </div>
    {%endif%}
      {%endif%}
  </div>
</nav>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark"></nav>
<!--END NAVBAR-->
{%block conant%}

{%endblock%}</body>
</html>

project/templates/index.html
{%extends 'base.html'%}
{%block conant%}
<div class="jumbotron devunder"  style="background:url({{url_for('static',filename='img/coming-soon.jpg')}});">
    <div class="display-3">This is an Index page</div>
    <div class="">Some text must enter here</div>
</div>
{%endblock%}

project/templates/undev.html
<div class="container">
    <center>
       UNDER DEVELOPMENT
    </center>
</div>