project/users/models.py
from project import db  # GET DATABASE OBJECT
# Take Reference of
# https://docs.sqlalchemy.org/en/13/orm/basic_relationships.html
from datetime import datetime

class Users(db.Model):
    uid = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.Text)
    email = db.Column(db.Text)
    password_text = db.Column(db.Text)
    reg_date = db.Column(db.DateTime, default=datetime.utcnow)
    project = db.relationship("project",backref='project',lazy='dynamic',secondary='share_project')
    def __init__(self, username, email, password_text):
        self.username = username
        self.email = email
        self.password_text = password_text

    def __repr__(self):
        return {
            'username': self.username,
            'email': self.email,
        }

project/users/views.py
import base64

from flask import url_for, render_template, Blueprint, request, redirect, session, flash
from project import User, db ,host_address
import requests
import json
import flask_login
from project.users.froms import user_registration, user_login, forget_password_form, new_password
from project.users.models import Users
from project.request_module.apicalls import user_api

user_print = Blueprint('users', __name__, template_folder='templates/users')
api = user_api()


@user_print.route('/')
@flask_login.login_required
def index():
    return render_template('users.html', users_=flask_login.current_user.id)


@user_print.route('/signup', methods=['GET', 'POST'])
def registration():
    form = user_registration(request.form)
    flask_login.logout_user()
    Error_ = ""
    if request.method == 'POST':
        re_enter_pass = form.re_enter_pass.data
        password = form.password.data
        if (password == re_enter_pass):
            try:
                username = form.username.data
                email = form.email.data
                present = api.check_mail(email) #(json.loads((requests.get('{}/user_check/{}'.format(host_address,email))).text))['status']
                if not present:
                    res=api.register(username, email, password) #(json.loads((requests.post('{}/register/{}/{}/{}'.format(host_address,username, email, password))).text))['status']
                    if res:
                        return redirect(url_for('users.login'))
                Error_ = 'EXIST'
            except Exception as e:
                print(str(e))
                Error_ = 'VALUES_ERROR'
                return render_template('registration.html', form=form, Error_=Error_)
        else:
            Error_ = 'PASSWORD_NOT_MATCH'
            return render_template('registration.html', form=form, Error_=Error_)
    return render_template('registration.html', form=form, Error_=Error_)


@user_print.route('/signin', methods=['GET', 'POST'])
def login():
    form = user_login()
    Error_ = ""
    if request.method == 'POST':
        try:
            email_ = form.email.data
            password = form.password.data
            if len(email_) == 0 and len(password) == 0:
                return render_template('login.html', form=form, Error_=3)#no input
            else:
                print('here input' + email_)
                res = api.login(email_, password)#json.loads((requests.get('{}/login/{}/{}'.format(host_address,email_, password))).text)
                present = res['status']
                if present:
                    session['uid'] = res['user_id']
                    session['username'] = res['username']
                    user = User()
                    user.id = email_
                    print(flask_login.current_user.is_authenticated)
                    flask_login.login_user(user)
                    return redirect(url_for('users.index'))
                Error_ = 1 # not valid
                return render_template('login.html', form=form, Error_=Error_)
        except KeyError:
            Error_ = 2 # 'ERROR_ON_USER_KEY'
        except Exception as e:
            Error_ = 'ok'+str(e)
    print(Error_)
    if flask_login.current_user.is_authenticated:
        return redirect(url_for('users.index'))
    else:
        return render_template('login.html', form=form, Error_=Error_)


@user_print.route('/logout')
def logout():
    print('in logout')
    flask_login.logout_user()
    return redirect(url_for('users.login'))

@user_print.route('/forget_password',methods=['GET','POST'])
def forget_password():
    form = forget_password_form()
    if request.method == 'POST':
        req = {'mail_id': str(form.mail_id.data)}
        res = api.send_forget_pass(json.dumps(req))#json.loads(requests.post(f'{host_address}/project/share', json.dumps(req)).text)
        print(str(res))
        if res['status']:
            flash('Link Shared Successfully!')
        else:
            flash('Can\'t reach to your mail. Link is not Shared!')
    return render_template('forget_password.html',form=form)

@user_print.route('/new_password/<string:data>')
def visiter(data):
    req ={'mail_id':str(data)}
    res= json.dumps(api.get_user_by_mail(json.dumps(req)))
    return redirect(url_for('users.change',data=res))

@user_print.route('/new_password_create/<string:data>',methods=['POST','GET'])
def change(data):
    form = new_password()
    data = json.loads(data)['user']
    print(data['username'])
    req=dict()
    status = False
    ERROR =""
    if request.method=='POST':
        new_pass1 = form.pass1.data
        new_pass2 = form.re_enter.data
        if len(new_pass1)>0 and len(new_pass2)>0:
            if new_pass1==new_pass2:
                req['mail_id'] =data['email']
                req['new_password'] =form.re_enter.data
                res = api.send_changed_pass(json.dumps(req))
                print(res)
                if(res['status']):
                    status = True
                else:
                    flash("Can't process your request.")
            else:
                flash("Password not matched.")
        else:
            flash("Please enter New password.")
    return render_template('new_password.html',form=form,data=data,status=status)

project/users/templates/users/forget_password.html
{%extends 'base.html'%}
{%block conant%}
<div class="jumbotron devunder" style="background:url({{url_for('static',filename='img/networking.jpg')}});" >
    <div class="display-3">Forget password</div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <form method="POST">
                        <div class="form-group">
                            {{form.mail_id.label}}
                            {{form.mail_id(class='form-control',placeholder='Mail id')}}
                        </div>
                        <div class="form-group">
                            {{form.submit(class='btn btn-block btn-success')}}
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            {% with messages = get_flashed_messages() %}
               {% if messages %}
                  {% for message in messages %}
                    {% if  message =='Link Shared Successfully!'%}
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                          <strong>Success!</strong> {{message}}
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                    {%else%}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                          <strong>Error!</strong> {{message}}<br>
                            Please Check mail id it must be registered with this system! and both password field must be same.
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                    {%endif%}
                  {% endfor %}
               {% endif %}
            {% endwith %}
        </div>
    </div>
</div>
{%endblock%}

project/users/templates/users/login.html
{%extends 'base.html'%}
{%block conant%}
<style>
    body{
    height: 100%;
    background-size: cover;
    background:url({{url_for('static',filename='img/login_room.jpg')}})no-repeat center center fixed;
    }
</style>
<div class="back">
    <div class="title-header" style="border-radius:0px;">
        <div class="display-4">Sign in</div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <div class="card">
                      <form method="POST">
                          <div class="card-header bg-dark">
                              <center> <img src="{{url_for('static',filename='logo.png')}}"/></center>
                          </div>
                          <div class="card-body">
                                  <div class="form-group">
                                      {{form.email.label}}
                                      {{form.email(class_='form-control',placeholder="Enter email")}}
                                  </div>
                                  <div class="form-group">
                                      {{form.password.label}}
                                      {{form.password(class_='form-control',placeholder="Password")}}
                                  </div>
                              <div style="text-align: right;">
                                  <a href="{{url_for('users.forget_password')}}">Forget Password</a>
                              </div>
                          </div>
                          <center>
                              {%if Error_ == 2 or Error_==1%}
                                  <div class="alert-danger" role="alert">
                                      <span>Please enter valid user name & password</span>
                                  </div>
                              {%elif Error_ == 3%}
                                  <div class="alert-danger" role="alert">
                                      <span>Please enter registered username & password</span>
                                  </div>
                              {%else%}
                                  <div class="alert-success" role="alert">
                                      <span>Welcome</span>
                                  </div>
                              {%endif%}
                          </center>
                          <div class="card-footer">
                                  <button type="submit" class="btn btn-primary">Sign in</button>
                              <a href="{{url_for('users.registration')}}"><input type="button" class="btn btn-warning" value="Sign up"/></a>
                          </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{%endblock%}

project/users/templates/users/new_password.html
{%extends 'base.html'%}
{%block conant%}
<div class="jumbotron devunder" style="background:url({{url_for('static',filename='img/networking.jpg')}});" >
    <div class="display-3">New password</div>
</div>

<div class="container">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                        {%if status==False%}
                    <form method="POST">
                        <div class="form-group">
                            {{data['username']}}
                        </div>
                        <div class="form-group">
                            {{form.pass1.label}}
                            {{form.pass1(class='form-control',placeholder='Mail id')}}
                        </div>
                        <div class="form-group">
                            {{form.re_enter.label}}
                            {{form.re_enter(class='form-control',placeholder='Mail id')}}
                        </div>
                        <div class="form-group">
                            {{form.submit(class='btn btn-block btn-success')}}
                        </div>
                    </form>
                        {%else%}
                        <div class="form-group">
                            <h3>Password is updated</h3>
                            <a href="{{url_for('users.login')}}" >
                                <button class="btn btn-block btn-success">
                                    Login
                                </button>
                            </a>
                        </div>
                        {%endif%}
                </div>
            </div>
        </div>
        <div class="col-md-4">
            {% with messages = get_flashed_messages() %}
               {% if messages %}
                  {% for message in messages %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                          <strong>Error!</strong> {{message}}<br>
                            Please Check mail id it must be registered with this system! and both field must be same.
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                  {% endfor %}
               {% endif %}
            {% endwith %}
        </div>
    </div>
</div>
{%endblock%}

project/users/templates/users/registration.html
{%extends 'base.html'%}
{%block conant%}
<style>
    .back{
    background-image:url({{url_for('static',filename='img/meeting.jpg')}});
    background-size: cover;
    background-repeat: no-repeat;
    }
</style>
<div class="back">
    <div class="title-header" style="border-radius:0px">
        <div class="display-4">Sign up</div>
    </div>
    <div class="container">
        <div class="row">
            <div class="col-md-4"></div>
            <div class="col-md-4"></div>
            <div class="col-md-4">
                <div class="card">
                      <form method="POST">
                          <div class="card-header bg-dark">
                              <center> <img src="{{url_for('static',filename='logo.png')}}"/></center>
                          </div>
                          <div class="card-body">
                                  <div class="form-group">
                                      {{form.username.label}}
                                      {{form.username(class_='form-control',placeholder="Enter User Name")}}
                                   </div>
                                  <div class="form-group">
                                      {{form.email.label}}
                                      {{form.email(class_='form-control',placeholder="Enter email")}}
                                  </div>
                                  <div class="form-group">
                                      {{form.password.label}}
                                      {{form.password(class_='form-control',placeholder="Password")}}
                                  </div>
                                  <div class="form-group">
                                      {{form.re_enter_pass.label}}
                                      {{form.re_enter_pass(class_='form-control',placeholder="Re-Enter Password")}}
                                  </div>
                                <center>
                                  <div class="alert-danger" role="alert">
                                    {%if Error_ == 'PASSWORD_NOT_MATCH'%}
                                      <span>Password not matched!</span>
                                    {%elif Error_ == 'VALUES_ERROR'%}
                                      <span>Can't possess your request please check your inputs</span>
                                    {%elif Error_ == 'EXIST'%}
                                      <span>User already Exist with '{{form.email.data}}'</span>
                                    {%endif%}
                                  </div>


                                </center>
                          </div>
                          <div class="card-footer">
                              {{form.submit(class_='btn btn-primary')}}
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
    </div>
{%endblock%}

project/users/templates/users/users.html
{%extends 'base.html'%}
{%block conant%}
<div class="jumbotron devunder" style="background:url({{url_for('static',filename='img/networking.jpg')}});" >
    <div class="display-3">User Dashboard</div>
    <div class="">Some text must enter here{{users_}}</div>
</div>
{% include 'undev.html' %}
{%endblock%}