project/task/models.py
from project import db
from project.users.models import Users
from project.project_module.models import project
from project.utils.conversions import to_date


class task_of_project(db.Model):
    tid = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.Text)
    details = db.Column(db.Text)
    start_date = db.Column(db.Date)
    end_date = db.Column(db.Date)
    state = db.Column(db.Integer)
    uid = db.Column('uid', db.Integer, db.ForeignKey(Users.uid))
    pid = db.Column('pid', db.Integer, db.ForeignKey(project.pid, ondelete='CASCADE'))
    # Creating relationship with project
    projects = db.relationship("project", backref="task_of_project")

    def __init__(self, task_):
        self.title = task_['title']
        self.details = task_['details']
        if task_ in ['start_date']:
            self.start_date = to_date(task_['start_date']).date()
        if task_ in ['end_date']:
            self.end_date = to_date(task_['end_date']).date()
        self.uid = task_['uid']
        self.pid = task_['pid']
        self.state = 0

project/task/forms.py
from wtforms import StringField, SubmitField, TextAreaField, DateField
from flask_wtf import FlaskForm


class CreateTaskForm(FlaskForm):
    title = StringField('Task title')
    details = TextAreaField('Details')
    start_date = DateField('Start date', id='start_date')
    end_date = DateField('End date', id='enddate')
    submit = SubmitField('Create')

project/task/views.py
from project.task.forms import CreateTaskForm
from flask import Blueprint, render_template, request, session, redirect, url_for
import json
from flask_login import login_required
from project.request_module.apicalls import task_api

task_view = Blueprint('task', __name__, template_folder='templates/task')

api = task_api()


@task_view.route('/<int:project_id>')
@login_required
def index(project_id):
    req = {'pid': project_id, 'uid': session['uid']}
    resp = api.get_all(req)
    print('>>{}'.format(str(resp)))
    count = dict()
    count['complete'] = 0
    count['remaining'] = 0
    count['all'] = 0
    if resp['status']:
        data = resp['tasks']
        for x in data:
            if x['state'] == 1:
                count['complete'] += 1
            elif x['state'] == 0:
                count['remaining'] += 1
            count['all'] += 1

    return render_template('task_home.html', project_id=project_id, count=count, project_name=resp['project_name'])


@task_view.route('/view/<int:list_id>/<int:project_id>')
@login_required
def view(list_id, project_id):
    req = {'pid': project_id, 'uid': session['uid']}
    tasks = list()
    print('\nREQUEST VIEW TASK-->{}'.format(str(req)))
    resp = api.get_all(req)
    print('\nRESPONSE VIEW TASK-->{}'.format(str(resp)))
    if resp['status']:
        tasks = resp['tasks']
    return render_template('list_of_task.html', list_id=list_id, project_id=project_id, tasks=tasks)


@task_view.route('/create/<int:project_id>', methods=['GET', 'POST'])
@login_required
def create_task(project_id):
    form = CreateTaskForm()
    if request.method == 'POST':
        req = dict()
        req['title'] = form.title.data
        req['details'] = form.details.data
        req['start_date'] = str(form.start_date.data)
        req['end_date'] = str(form.end_date.data)
        req['uid'] = session['uid']
        req['pid'] = project_id
        print('\nREQUEST CREATE TASK-->{}'.format(str(req)))
        resp = api.create(
            json.dumps(req))
        print('\nRESPONSE CREATE TASK-->{}'.format(str(resp)))
        if resp['status']:
            return redirect(url_for('task.index', project_id=project_id))

    return render_template('create_task.html', project_id=project_id, form=form)


@login_required
@task_view.route('/delete/<int:project_id>/<int:list_id>/<int:tid>')
def delete_task(project_id, list_id, tid):
    req = dict()
    req['uid'] = session['uid']
    req['pid'] = project_id
    req['tid'] = tid
    api.delete(req)
    return redirect(url_for('task.view', list_id=list_id, project_id=project_id))


@login_required
@task_view.route('/complete/<int:project_id>/<int:list_id>/<int:tid>')
def mark_complete(project_id, list_id, tid):
    req = dict()
    req['uid'] = session['uid']
    req['pid'] = project_id
    req['tid'] = tid
    api.complet_mark(req)
    return redirect(url_for('task.view', list_id=list_id, project_id=project_id))


@login_required
@task_view.route('/working/<int:project_id>/<int:list_id>/<int:tid>')
def mark_un_complete(project_id, list_id, tid):
    req = dict()
    req['uid'] = session['uid']
    req['pid'] = project_id
    req['tid'] = tid
    api.uncomplete_mark(req)
    return redirect(url_for('task.view', list_id=list_id, project_id=project_id))

project/task/templates/task/create_task.html
{%extends 'base.html'%}
{%block conant%}
<div class="title-header" style="border-radius:0px;">
    <div class="display-4">Create Task</div>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <form method="POST">
                <div class="card">
                    <div class="card-body">
                        <div class="form-group">
                            {{form.title.label}}
                            {{form.title(class='form-control')}}
                        </div>
                        <div class="form-group">
                            {{form.details.label}}
                            {{form.details(class='form-control')}}
                        </div>
                        <div class="form-group">
                            {{form.start_date.label}}
                            {{form.start_date(class='form-control')}}
                        </div>
                        <div class="form-group">
                            {{form.end_date.label}}
                            {{form.end_date(class='form-control')}}
                        </div>
                        <div class="form-group">
                            {{form.submit(class='btn btn-success')}}
                        </div>
                </div>
            </div>
            </form>
        </div>
        <div class="col-md-4"></div>
    </div>
</div>

<script>
    $(document).ready(function() {
    $('#start_date').prop('type', 'date');
    $('#enddate').prop('type', 'date');
    });
</script>
{%endblock%}

project/task/templates/task/list_of_task.html
{%extends 'base.html'%}
{%block conant%}
<div class="jumbotron devunder" style="background:url({{url_for('static',filename='img/coming-soon.jpg')}});">
    <div class="display-3">Tasks list</div>
    <a href="{{url_for('task.create_task',project_id=project_id)}}" > <button id="read-more" style="margin:2px" class="btn btn-primary float-md-left">Create Task <i class="fa fa-plus-square" aria-hidden="true"></i></button></a>
    <a href="{{url_for('task.index',project_id=project_id)}}" > <button style="margin:2px" class="btn btn-primary float-md-left">Task List <i class="fa fa-tasks" aria-hidden="true"></i></button></a>
</div>
<div class="container">
    <div class="row">
            {%set exists = []%}
            {% if (tasks|length==0)%}
            {%else%}
                {%for x in tasks%}
                    {%if x['state']==list_id or list_id==3 %}
                    {%if exists.append(1)%}{%endif%}
                    <div class="col-md-3">
                        <div class="card " data-toggle="modal" data-target="#{{x['tid']}}">
                            <h6 class="card-header one_line">{{x['title']}}</h6>
                            <div class="card-body one_line">
                                {{x['details']}}
                            </div>
                            <h6 class="card-header one_line">
                                <center>
                                {%if x['state']==1%}
                                    <span class="badge badge-success">Complete</span>
                                {%else%}
                                    <span class="badge badge-warning">Working</span>
                                {%endif%}
                                </center>
                            </h6>
                        </div>
                    </div>

<!-- Modal -->
            <div class="modal fade" id="{{x['tid']}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">{{x['title']}}</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">
                        {%if x['state']==1%}
                            <span class="badge badge-success">Complete</span>
                        {%else%}
                            <span class="badge badge-warning">Working</span>
                        {%endif%}<br>
                      {{x['details']}}
                  </div>
                  <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                        {%if x['state']==1%}
                      <a href="{{url_for('task.mark_un_complete',list_id=list_id,project_id=project_id,tid=x['tid'])}}"> <button type="button" class="btn btn-warning">Mark Working</button></a>
                        {%else%}
                            <a href="{{url_for('task.mark_complete',list_id=list_id,project_id=project_id,tid=x['tid'])}}"> <button type="button" class="btn btn-success">Mark Complete</button></a>
                        {%endif%}
                      <a href="{{url_for('task.delete_task',list_id=list_id,project_id=project_id,tid=x['tid'])}}"> <button type="button" class="btn btn-danger">Delete</button></a>
                  </div>
                </div>
              </div>
            </div>
        {%endif%}
                {%endfor%}
            {%endif%}
        {% if not exists %}
        <h4 class="display-4">
            {%if list_id==0%}
                NoRemaining Task
            {%elif list_id==1%}
                No Completed Task
            {%else%}
                No Task
            {%endif%}
        </h4>
        <img src="{{url_for('static',filename='img/noresult.svg')}}" height="90px" width="90px"/>
        {%endif%}

    </div>
</div>


{%endblock%}

project/task/templates/task/task_home.html
{%extends 'base.html'%}
{%block conant%}
<div class="jumbotron devunder" style="background:url({{url_for('static',filename='img/coming-soon.jpg')}});">
    <div class="display-3">Tasks of {{project_name}}</div>
    <a href="{{url_for('task.create_task',project_id=project_id)}}" > <button id="read-more" style="margin:2px" class="btn btn-primary float-md-left">Create Task <i class="fa fa-plus-square" aria-hidden="true"></i></button></a>
</div>
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <div class="card">
                <a href="{{url_for('task.view',list_id=3,project_id=project_id)}}">
                    <div class="card-body">
                        <center>
                            <h3><small>All Task</small></h3>
                            <h2><span class="badge badge-secondary">{{count['all']}}</span></h2>
                        </center>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <a href="{{url_for('task.view',list_id=0,project_id=project_id)}}">
                    <div class="card-body">
                        <center>
                            <h3><small>Remaining Task</small></h3>
                            <h2><span class="badge badge-secondary">{{count['remaining']}}</span></h2>
                        </center>
                    </div>
                </a>
            </div>
        </div>
        <div class="col-md-4">
            <div class="card">
                <a href="{{url_for('task.view',list_id=1,project_id=project_id)}}">
                    <div class="card-body">
                        <center>
                            <h3><small>Completed Task</small></h3>
                            <h2><span class="badge badge-secondary">{{count['complete']}}</span></h2>
                        </center>
                    </div>
                </a>
            </div>
        </div>
    </div>
</div>

{%endblock%}