project/project_module/views.py
from flask import request, redirect, render_template, Blueprint, json, url_for, session, flash
from flask_login import login_required
from project.project_module.forms import AddProject, ShareProjectForm
from project.project_module.models import project_wapper
from project.utils.statics_data import date_in_result, not_in_result
from project.utils.conversions import to_date_time, to_date, with_utf
from project.request_module.apicalls import project_api

project_print = Blueprint('project', __name__, template_folder='templates/project_module')

api = project_api()


@project_print.route('/')
@login_required
def index():
    uid_send = dict()
    uid_send["uid"] = session['uid']
    print(json.dumps(uid_send))
    data = api.get_all(session['uid'])
    var = list()
    try:
        var = data['all_projects']
        print(var)
    except Exception:
        pass
    return render_template('project_module.html', var=var)


@project_print.route('/new', methods=['GET', 'POST'])
@login_required
def new_project():
    form = AddProject()
    if request.method == 'POST':
        project_ = dict()
        project_['project_name'] = form.project_name.data
        project_['project_description'] = form.project_description.data
        project_['project_starting_date'] = form.project_starting_date.data
        project_['project_releasing'] = form.project_releasing.data
        project_['customer_name'] = form.customer_name.data
        project_['customer_contact'] = form.customer_contact.data
        project_['customer_mail'] = form.customer_mail.data
        project_['customer_company_name'] = form.customer_company_name.data
        project_['customer_site'] = form.customer_site.data
        project_['uid'] = session['uid']
        project_obj = project_wapper(project_)
        print('==>>REQUEST : {}'.format(str(project_obj.__dict__)))
        data = api.create(json.dumps(project_obj.__dict__))
        print('{} response '.format(data))
        if data['status']:
            return redirect(url_for('project.index'))
    return render_template('new_project.html', form=form)


@project_print.route('/edit/<int:pid>', methods=['GET', 'POST'])
@login_required
def edit(pid):
    form = AddProject()
    req = {'pid': pid, 'uid': session['uid']}
    res = api.view(req)
    print('RESPONSE : {}'.format(str(res)))
    data = res['all_projects'][0]
    if len(res['all_projects']) == 0:
        return render_template('project_view.html', data='NO')
    if len(data) == 0:
        return redirect(url_for('project.index'))
    else:
        print(type(data))
        if request.method == 'GET':
            for key, val in data.items():
                if key in ['project_name', 'project_description', 'customer_contact', 'customer_company_name',
                           'customer_site', 'customer_mail', 'customer_name']:
                    form[key].data = val
                if key in ['project_starting_date', 'project_releasing']:
                    form[key].value = with_utf(to_date(val))
                    print('KEY >{} {}'.format(type(to_date_time(val)), val))

    if request.method == 'POST':
        project_ = dict()
        for key, val in data.items():
            if not key in not_in_result:
                project_[key] = form[key].data
        project_['uid'] = session['uid']
        project_obj = project_wapper(project_)
        print('==>>REQUEST : {}'.format(str(project_obj.__dict__)))
        up_req = {
            'user': req,
            'project': project_obj.__dict__
        }
        print('\n\n------<>{}'.format(up_req))
        data = api.save_edited(json.dumps(up_req))
        print('{} response '.format(data))
        if data['status']:
            return redirect(url_for('project.index'))
    return render_template('edit_project.html', form=form)


@project_print.route('/view')
@login_required
def project_view():
    req = {'pid': request.args.get('pid'), 'uid': session['uid']}
    res = api.view(req)
    users = api.get_project_users(req)
    print('RESPONSE : {}'.format(str(res)))
    if len(res['all_projects']) == 0:
        return render_template('project_view.html', data='NO')
    for x in date_in_result:
        res['all_projects'][0][x] = to_date_time(res['all_projects'][0][x])
    return render_template('project_view.html', data=res['all_projects'][0], users=users['users'])


@project_print.route('/delete')
@login_required
def delete():
    req = {'pid': request.args.get('pid'), 'uid': session['uid']}
    res = api.delete(req)
    print('RESPONSE : {}'.format(str(res)))
    if res['status']:
        return redirect(url_for('project.index'))
    return redirect(url_for('project.project_view'))


@project_print.route('/share/<int:project_id>', methods=['GET', 'POST'])
@login_required
def share(project_id):
    form = ShareProjectForm()
    if request.method == 'POST':
        req = {'pid': project_id, 'uid': session['uid'], 'mail_id': str(form.mail_id.data)}
        res = api.share(req)
        print(str(res))
        if res['status']:
            flash('Project Shared Successfully!')
        else:
            flash('Project Not Shared!')
    return render_template('share_project.html', form=form)

project/project_module/templates/project_module/edit_project.html
{%extends 'base.html'%}
{%block conant%}
    <div class="title-header" style="border-radius:0px;">
        <div class="display-4">Edit Project</div>
    </div>
    <div class="container">
        <form method="POST">
            <div class="row">
                    <div class="left_border col-md-6 bg-light">
                        <h3 class="display-4" style="font-size:30px">Project Details</h3>
                        <!--Project Details-->
                      <div class="form-group">
                          {{form.project_name.label}}
                          {{form.project_name(class_='form-control',placeholder="Name")}}
                      </div>
                      <div class="form-group">
                          {{form.project_description.label}}
                          {{form.project_description(class_='form-control',placeholder="Description")}}
                      </div>
                      <div class="form-group">
                          {{form.project_starting_date.label}}
                          {{form.project_starting_date(class_='form-control',placeholder="Starting Date")}}
                      </div>
                      <div class="form-group">
                          {{form.project_releasing.label}}
                          {{form.project_releasing(class_='form-control',placeholder="Releasing Date")}}
                      </div>
                    </div>
                    <div class="left_border col-md-6">
                        <h3 class="display-4" style="font-size:30px">Customer Details</h3>
                        <!--Customer Details-->
                      <div class="form-group">
                          {{form.customer_name.label}}
                          {{form.customer_name(class_='form-control',placeholder="Name")}}
                      </div>
                      <div class="form-group">
                          {{form.customer_contact.label}}
                          {{form.customer_contact(class_='form-control',placeholder="Contact number")}}
                      </div>
                      <div class="form-group">
                          {{form.customer_mail.label}}
                          {{form.customer_mail(class_='form-control',placeholder="Mail")}}
                      </div>
                      <div class="form-group">
                          {{form.customer_company_name.label}}
                          {{form.customer_company_name(class_='form-control',placeholder="Company Name")}}
                      </div>
                      <div class="form-group">
                          {{form.customer_site.label}}
                          {{form.customer_site(class_='form-control',placeholder="Site")}}
                      </div>
                    </div>
            </div>
            <div class="card-footer" style="margin-left:-15px;margin-right:-15px">
                {{form.submit_save(class='btn btn-outline-primary')}}
            </div>
        </form>
    </div>
<script>
    $(document).ready(function() {
    $('#start_date').prop('type', 'date');
    $('#releasing_date').prop('type', 'date');
    });
</script>
{%endblock%}

project/project_module/templates/project_module/new_project.html
{%extends 'base.html'%}
{%block conant%}
    <div class="title-header" style="border-radius:0px;">
        <div class="display-4">Create new Project</div>
    </div>
    <div class="container">
        <form method="POST">
            <div class="row">
                    <div class="left_border col-md-6 bg-light">
                        <h3 class="display-4" style="font-size:30px">Project Details</h3>
                        <!--Project Details-->
                      <div class="form-group">
                          {{form.project_name.label}}
                          {{form.project_name(class_='form-control',placeholder="Name")}}
                      </div>
                      <div class="form-group">
                          {{form.project_description.label}}
                          {{form.project_description(class_='form-control',placeholder="Description")}}
                      </div>
                      <div class="form-group">
                          {{form.project_starting_date.label}}
                          {{form.project_starting_date(class_='form-control',placeholder="Starting Date")}}
                      </div>
                      <div class="form-group">
                          {{form.project_releasing.label}}
                          {{form.project_releasing(class_='form-control',placeholder="Releasing Date")}}
                      </div>
                    </div>
                    <div class="left_border col-md-6">
                        <h3 class="display-4" style="font-size:30px">Customer Details</h3>
                        <!--Customer Details-->
                      <div class="form-group">
                          {{form.customer_name.label}}
                          {{form.customer_name(class_='form-control',placeholder="Name")}}
                      </div>
                      <div class="form-group">
                          {{form.customer_contact.label}}
                          {{form.customer_contact(class_='form-control',placeholder="Contact number")}}
                      </div>
                      <div class="form-group">
                          {{form.customer_mail.label}}
                          {{form.customer_mail(class_='form-control',placeholder="Mail")}}
                      </div>
                      <div class="form-group">
                          {{form.customer_company_name.label}}
                          {{form.customer_company_name(class_='form-control',placeholder="Company Name")}}
                      </div>
                      <div class="form-group">
                          {{form.customer_site.label}}
                          {{form.customer_site(class_='form-control',placeholder="Site")}}
                      </div>
                    </div>
            </div>
            <div class="card-footer" style="margin-left:-15px;margin-right:-15px">
                {{form.submit(class='btn btn-outline-primary')}}
            </div>
        </form>
    </div>
<script>
    $(document).ready(function() {
    $('#start_date').prop('type', 'date');
    $('#releasing_date').prop('type', 'date');
    });
</script>
{%endblock%}

project/project_module/templates/project_module/project_module.html
{% extends 'base.html'%}
{%block conant%}
<div class="jumbotron devunder" style="background:url({{url_for('static',filename='img/coming-soon.jpg')}});">
    <div class="display-3">All Projects</div>
</div>
<div class="container">
    <div class="card">
        <div class="card-footer">
            <a href="{{url_for('project.new_project')}}" class="btn btn-outline-primary">add new project</a>
            <a href="#" class="btn btn-outline-info">status</a>
            <a href="#" class="btn btn-outline-info">Releasing this months</a>
        </div>
    </div>
    <!--HEADER of the Project actions-->

    <div>
        {% if var|length==0 %}
        <center>
            <h1 class="display-4">Create Project</h1>
            <span>-- No Project is created --</span><br>
            <img src="{{url_for('static',filename='img/noresult.svg')}}" height="90px" width="90px"/>
        </center>
        {%else%}
            {%for pro in var[::-1]%}
            <div class="card">

                <div class="card-body btn-outline-info">
                    <a href="{{url_for('project.project_view',pid=pro.pid)}}" style="color:black">
                        <h5 class="card-title">{{pro.project_name}}</h5>
                        <p class="card-text one_line">{{pro.project_description}}</p>
                    </a>
                </div>
            </div>
            {%endfor%}
        {%endif%}
    </div>


</div>


{%endblock%}

project/project_module/templates/project_module/project_view.html
{% extends 'base.html' %}
{% block conant%}
<div class="jumbotron devunder" style="background:url({{url_for('static',filename='img/coming-soon.jpg')}});">
    {% if data == 'NO'%}
    <div class="display-3">NO PROJECT</div>
    <div>Description: <span>This project is Not created by you!</span></div>
</div>
    {%else%}
    <div class="display-3">{{data.project_name}}</div>
    <a href="{{url_for('task.index',project_id=data.pid)}}" > <button id="read-more" style="margin:2px" class="btn btn-primary float-md-left">Tasks <i class="fa fa-tasks" aria-hidden="true"></i></button></a>
    {%if (data.uid==session['uid'])%}
    <a href="{{url_for('project.edit',pid=data.pid)}}" > <button id="read-more" style="margin:2px" class="btn btn-primary float-md-right">Edit <i class="fa fa-pencil-square-o" aria-hidden="true"></i></button></a>
    <button  data-toggle="modal" data-target="#exampleModal" style="margin:2px" class="btn btn-primary float-md-right">Delete <i class="fa fa-trash" aria-hidden="true"></i></button>
    <a href="{{url_for('project.share',project_id=data.pid)}}" > <button id="read-more" style="margin:2px" class="btn btn-primary float-md-right">Share <i class="fa fa-share" aria-hidden="true"></i></button></a>
    {%endif%}

</div>
<div class="container">
    <div class="row">
    <div class="card col-md-6">
        <div class="card-body">
            <h5 class="card-title">Project details</h5>
            <div class="card-text">Date: <span>{{data.project_starting_date[:-9] }}</span> to <span>{{data.project_releasing[:-9]}}</span></div>
        </div>
    </div>

    <div class="card col-md-6">
        <div class="card-body">
            <h5 class="card-title">Customer details</h5>
            <div class="card-text">Person Name: <span>{{data.customer_name}}</span></div>
            <div class="card-text">Contact: <span>{{data.customer_contact}}</span> | <span>{{data.customer_mail}}</span></div>
                    <div class="card-text">Company:<span>{{data.customer_company_name}}</span><br><a href="#">{{data.customer_site}}</a></div>
        </div>
    </div>
    </div>
    <div class="row">
        <div class="card col-md-12">
            <div class="card-body">
                <strong>Description:</strong> <span>{{data.project_description}}</span>

            </div>
        </div>
    </div>
    <div class="row">
        <h3 class="card-body">Team</h3>
        <div class="card col-md-12">
            <div class="row">
                {%for u in users%}
                <div class="col-md-3 align-items-stretch card card-body">
                    <div class="">
                        <div class="">
                            <center>
                                <img width="60" height="60" src="{{url_for('static',filename='img/profile.png')}}">
                            </center>
                            <div class="card-body">
                                <center>
                                    {%if (data.uid==u.uid)%}
                                    <small><span class="badge badge-success">Owner</span></small>
                                    {%endif%}
                                    {%if(u.uid==session['uid'])%}
                                    <small><span class="badge badge-danger">You</span></small>
                                    {%endif%}
                                    <h5>{{u.username}}</h5>
                                    <small>{{u.email}}</small>
                                </center>
                            </div>
                        </div>
                    </div>
                    </div>
                {%endfor%}
            </div>
        </div>
    </div>
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">You Really wants to delete?</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
          <strong>{{data.project_name}}</strong> is belongs to <strong>{{data.customer_name}}</strong> please give your selection.
          <br>
          <strong>Note:</strong>No data will recover after deleting this project.
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <a href="{{url_for('project.delete',pid=data.pid)}}"> <button type="button" class="btn btn-primary">Delete anyway</button></a>
      </div>
    </div>
  </div>
</div>
{%endif%}
{% endblock %}

project/project_module/templates/project_module/share_project.html
{%extends 'base.html'%}
{%block conant%}
    <div class="title-header" style="border-radius:0px;">
        <div class="display-4">Share Project</div>
    </div>
<div class="container">
    <div class="row">
        <div class="col-md-4"></div>
        <div class="col-md-4">
            <div class="card">
                <div class="card-body">
                    <form method="POST">
                        <div class="form-group">
                            {{form.mail_id.label}}
                            {{form.mail_id(class='form-control',placeholder='Mail id')}}
                        </div>
                        <div class="form-group">
                            {{form.submit(class='btn btn-block btn-success')}}
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-4">
            {% with messages = get_flashed_messages() %}
               {% if messages %}
                  {% for message in messages %}
                    {% if  message =='Project Shared Successfully!'%}
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                          <strong>Success!</strong> {{message}}
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                    {%else%}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                          <strong>Error!</strong> {{message}}<br>
                            Please Check mail id it must be registered with this system!
                          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                          </button>
                        </div>
                    {%endif%}
                  {% endfor %}
               {% endif %}
            {% endwith %}
        </div>
    </div>
</div>
{%endblock%}